/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Container;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ADMIN
 */
public class frmRolsecretaria extends javax.swing.JFrame {

    /**
     * Creates new form frmRolsecretaria
     */
    public Image imagenFondo;
    public URL fondo;
    public static frmRegistrosolicitante frmRegSol;
    public static frmConsultarSolicitante frmConSol;
    public static GenerarReportes frmGenRep;
    public static frmAprobarCertificado frmAprCer;
//    Panel p;

    public frmRolsecretaria() {

        JPanelBackground panelFondo = new JPanelBackground();
        this.setContentPane(panelFondo);
        panelFondo.setBackground();
        panelFondo.setOpaque(false);
        initComponents();
        this.setLayout(new GridBagLayout());
        this.setLocationRelativeTo(null);
        lblusu.setVisible(false);

    }
    public JPanel panel = new JPanel() {
        public void paintComponent(Graphics g) {
            g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabeltitulo = new javax.swing.JLabel();
        jButtonnuevousuario = new javax.swing.JButton();
        jButtonconsultarusuario = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jButtonconsultarusuario1 = new javax.swing.JButton();
        jButtonreportes = new javax.swing.JButton();
        lblusu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setOpaque(false);

        jLabeltitulo.setBackground(new java.awt.Color(0, 0, 0));
        jLabeltitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabeltitulo.setText("BIENVENIDO A CERTIBOYACA TE ENCUENTRAS EN EL ROL SECRETARIA DE GOBIERNO");

        jButtonnuevousuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonnuevousuario.setText("Registrar Ciudadano");
        jButtonnuevousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnuevousuarioActionPerformed(evt);
            }
        });

        jButtonconsultarusuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonconsultarusuario.setText("Consultar Ciudadano");
        jButtonconsultarusuario.setAutoscrolls(true);
        jButtonconsultarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonconsultarusuarioActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 0, 51));
        salir.setText("SALIR");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jButtonconsultarusuario1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonconsultarusuario1.setText("Aprobar Certificado");
        jButtonconsultarusuario1.setAutoscrolls(true);
        jButtonconsultarusuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonconsultarusuario1ActionPerformed(evt);
            }
        });

        jButtonreportes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonreportes.setText("Generar Reportes");
        jButtonreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonreportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblusu)
                .addContainerGap(1070, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(970, 970, 970)
                            .addComponent(salir))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabeltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonnuevousuario, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(jButtonconsultarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)
                            .addComponent(jButtonconsultarusuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(400, 400, 400)
                            .addComponent(jButtonreportes, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 5, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblusu)
                .addContainerGap(498, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(salir)
                    .addGap(75, 75, 75)
                    .addComponent(jLabeltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonconsultarusuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonnuevousuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonconsultarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(40, 40, 40)
                    .addComponent(jButtonreportes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 35, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonnuevousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnuevousuarioActionPerformed
        // TODO add your handling code here:
        if (frmRegSol == null) {
            frmRegSol = new frmRegistrosolicitante();

            frmRegSol.setVisible(true);
            frmRegSol.txtusu.setText(lblusu.getText());
        }
    }//GEN-LAST:event_jButtonnuevousuarioActionPerformed

    private void jButtonconsultarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonconsultarusuarioActionPerformed
        // TODO add your handling code here:
        if (frmConSol == null) {
            frmConSol = new frmConsultarSolicitante();
            frmConSol.lblIdUsu.setText(lblusu.getText());
            frmConSol.setVisible(true);
        }
    }//GEN-LAST:event_jButtonconsultarusuarioActionPerformed

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_salirMouseClicked

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void jButtonconsultarusuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonconsultarusuario1ActionPerformed
        // TODO add your handling code here:
        if (frmAprCer == null) {
            frmAprCer = new frmAprobarCertificado();
            frmAprCer.lblIdUsu.setText(lblusu.getText());
            frmAprCer.setVisible(true);
        }
    }//GEN-LAST:event_jButtonconsultarusuario1ActionPerformed

    private void jButtonreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonreportesActionPerformed
        // TODO add your handling code here:
        if (frmGenRep == null) {
            frmGenRep = new GenerarReportes();
            frmGenRep.setVisible(true);
        }
    }//GEN-LAST:event_jButtonreportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRolsecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRolsecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRolsecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRolsecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRolsecretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonconsultarusuario;
    private javax.swing.JButton jButtonconsultarusuario1;
    private javax.swing.JButton jButtonnuevousuario;
    private javax.swing.JButton jButtonreportes;
    private javax.swing.JLabel jLabeltitulo;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblusu;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
