/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.ControladorCiudadanos;
import Modelo.Ciudadanos;
import Modelo.ConsultasCiudadanos;
import Modelo.Departamentos;
import Modelo.Municipios;
import Modelo.Tramites;
import java.awt.GridBagLayout;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


/**
 *
 * @author ADMIN
 */
public class frmRegistrosolicitante extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistrosolicitante
     */
    
    
    private int count = 0;
    public frmRegistrosolicitante() {
        JPanelBackground panelFondo = new JPanelBackground();
        this.setContentPane(panelFondo);
        panelFondo.setBackground();
        panelFondo.setOpaque(false);
        initComponents();
        this.setLayout(new GridBagLayout());
        this.setLocationRelativeTo(null);
        
        Departamentos dep = new Departamentos();
        DefaultComboBoxModel cbomodel = new DefaultComboBoxModel(dep.mostrarDepartamentos());
        cbodepartamentos.setModel(cbomodel);

        Tramites tra = new Tramites();
        DefaultComboBoxModel cbomodel1 = new DefaultComboBoxModel(tra.mostrarTramites());
        cboTramite.setModel(cbomodel1);

        txtDepartamento.setVisible(false);
        txtMunicipio.setVisible(false);
        txttramite.setVisible(false);
        txtusu.setVisible(false);
    }
    
    void limpiar() {
        txtPrimerNombre.setText(null);
        txtSegundoNombre.setText(null);
        txtPrimerApellido.setText(null);
        txtSegundoApellido.setText(null);
        txtDireccion.setText(null);
        txtCorreo.setText(null);
        txtDepartamento.setText("0");
        txtMunicipio.setText("0");
        txttramite.setText("0");
        txtIdentificacion.setText(null);
        chxCertificadoE.setSelected(false);
        chxCertificadoJAC.setSelected(false);
        chxSisben.setSelected(false);
        chxOtros.setSelected(false);
        cboTramite.setSelectedIndex(0);
        cbodepartamentos.setSelectedIndex(0);
        if (cbomunicipios.getSelectedIndex() > 0) {
            cbomunicipios.remove(cbomunicipios.getSelectedIndex());
            cbomunicipios.getSelectedIndex();
        }
        observacion.setText(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabeltitulo = new javax.swing.JLabel();
        txtusu = new javax.swing.JTextField();
        nombresolicitante = new javax.swing.JLabel();
        txtPrimerNombre = new javax.swing.JTextField();
        primerapellido = new javax.swing.JLabel();
        txtPrimerApellido = new javax.swing.JTextField();
        segundonombresolici = new javax.swing.JLabel();
        txtSegundoNombre = new javax.swing.JTextField();
        segundoapellido = new javax.swing.JLabel();
        txtSegundoApellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        Expedida = new javax.swing.JLabel();
        cbodepartamentos = new javax.swing.JComboBox<>();
        txtDepartamento = new javax.swing.JTextField();
        cbomunicipios = new javax.swing.JComboBox<>();
        txtMunicipio = new javax.swing.JTextField();
        Direcc = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboTramite = new javax.swing.JComboBox<>();
        txttramite = new javax.swing.JTextField();
        chxSisben = new javax.swing.JCheckBox();
        chxCertificadoE = new javax.swing.JCheckBox();
        chxCertificadoJAC = new javax.swing.JCheckBox();
        chxOtros = new javax.swing.JCheckBox();
        observacion = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setOpaque(false);

        jLabeltitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabeltitulo.setText("BIENVENIDO AL MÓDULO DEL REGISTRO DEL SOLICITANTE, POR FAVOR INGRESE LOS DATOS");

        nombresolicitante.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nombresolicitante.setText("Primer nombre");

        txtPrimerNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        primerapellido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        primerapellido.setText("Primer apellido");

        txtPrimerApellido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        segundonombresolici.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        segundonombresolici.setText("Segundo nombre ");

        txtSegundoNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        segundoapellido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        segundoapellido.setText("Segundo apellido");

        txtSegundoApellido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSegundoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegundoApellidoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Identificación");

        txtIdentificacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        Expedida.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Expedida.setText("Departamento exp.");

        cbodepartamentos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbodepartamentos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbodepartamentosItemStateChanged(evt);
            }
        });

        txtDepartamento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDepartamento.setText("0");

        cbomunicipios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbomunicipios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione municipio" }));
        cbomunicipios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbomunicipiosItemStateChanged(evt);
            }
        });

        txtMunicipio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtMunicipio.setText("0");

        Direcc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Direcc.setText("Lugar de Residencia:");

        txtDireccion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        Email.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Email.setText("Correo Electrónico");

        txtCorreo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Tramite:");

        cboTramite.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cboTramite.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTramiteItemStateChanged(evt);
            }
        });

        txttramite.setText("0");

        chxSisben.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        chxSisben.setText("¿Presenta Sisben?");
        chxSisben.setInheritsPopupMenu(true);
        chxSisben.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chxSisbenItemStateChanged(evt);
            }
        });
        chxSisben.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxSisbenActionPerformed(evt);
            }
        });

        chxCertificadoE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        chxCertificadoE.setText("¿Presenta Certificado Electoral?");
        chxCertificadoE.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chxCertificadoEItemStateChanged(evt);
            }
        });
        chxCertificadoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxCertificadoEActionPerformed(evt);
            }
        });

        chxCertificadoJAC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        chxCertificadoJAC.setText("Certificado J.A.C");
        chxCertificadoJAC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chxCertificadoJACItemStateChanged(evt);
            }
        });

        chxOtros.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        chxOtros.setText("Otros Soportes");
        chxOtros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chxOtrosItemStateChanged(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelar.setText("LIMPIAR");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("CERRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabeltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtusu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(nombresolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(txtPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(90, 90, 90)
                            .addComponent(segundonombresolici, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(txtSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(primerapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(txtPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(120, 120, 120)
                            .addComponent(segundoapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(txtSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel1)
                            .addGap(10, 10, 10)
                            .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(Expedida)
                            .addGap(5, 5, 5)
                            .addComponent(cbodepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(110, 110, 110)
                            .addComponent(cbomunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(610, 610, 610)
                            .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(110, 110, 110)
                            .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(170, 170, 170)
                            .addComponent(Direcc, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(530, 530, 530)
                            .addComponent(jLabel2)
                            .addGap(10, 10, 10)
                            .addComponent(cboTramite, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(txttramite, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chxSisben)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(930, 930, 930)
                                    .addComponent(chxOtros))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(670, 670, 670)
                                    .addComponent(chxCertificadoJAC))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(260, 260, 260)
                                    .addComponent(chxCertificadoE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(observacion, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(270, 270, 270)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabeltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(txtusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nombresolicitante)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(txtPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(segundonombresolici)
                        .addComponent(txtSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(primerapellido)
                        .addComponent(txtPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(segundoapellido)
                        .addComponent(txtSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Expedida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbodepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbomunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Direcc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cboTramite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttramite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chxSisben)
                        .addComponent(chxOtros)
                        .addComponent(chxCertificadoJAC)
                        .addComponent(chxCertificadoE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(observacion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(20, 20, 20)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSegundoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegundoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegundoApellidoActionPerformed

    private void cbodepartamentosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbodepartamentosItemStateChanged
        // TODO add your handling code here:

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Departamentos dep = (Departamentos) cbodepartamentos.getSelectedItem();
            Municipios mun = new Municipios();
            DefaultComboBoxModel modMun = new DefaultComboBoxModel(mun.mostrarMunicipios(dep.getId()));
            cbomunicipios.setModel(modMun);

        }
    }//GEN-LAST:event_cbodepartamentosItemStateChanged

    private void cbomunicipiosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbomunicipiosItemStateChanged
        // TODO add your handling code here:

        Departamentos dep = (Departamentos) cbodepartamentos.getSelectedItem();
        Municipios mun = (Municipios) cbomunicipios.getSelectedItem();
        txtDepartamento.setText(String.valueOf(dep.getId()));
        txtMunicipio.setText(String.valueOf(mun.getId()));
    }//GEN-LAST:event_cbomunicipiosItemStateChanged

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void cboTramiteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTramiteItemStateChanged
        // TODO add your handling code here:

        Tramites tra = (Tramites) cboTramite.getSelectedItem();
        System.out.println(tra.getId());
        txttramite.setText("" + tra.getId());
    }//GEN-LAST:event_cboTramiteItemStateChanged

    private void chxSisbenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chxSisbenItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            count++;
        } else {
            count--;
        }
    }//GEN-LAST:event_chxSisbenItemStateChanged

    private void chxSisbenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxSisbenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chxSisbenActionPerformed

    private void chxCertificadoEItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chxCertificadoEItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            count++;
        } else {
            count--;
        }
    }//GEN-LAST:event_chxCertificadoEItemStateChanged

    private void chxCertificadoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxCertificadoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chxCertificadoEActionPerformed

    private void chxCertificadoJACItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chxCertificadoJACItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            count++;
        } else {
            count--;
        }
    }//GEN-LAST:event_chxCertificadoJACItemStateChanged

    private void chxOtrosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chxOtrosItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            count++;
        } else {
            count--;
        }
    }//GEN-LAST:event_chxOtrosItemStateChanged

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        Ciudadanos mod = new Ciudadanos();
        ConsultasCiudadanos modC = new ConsultasCiudadanos();

        ControladorCiudadanos ctrl = new ControladorCiudadanos(mod, modC);

        int certificadoE = 0, certificadoJAC = 0, sisben = 0, otros = 0;
        if (chxCertificadoE.isSelected()) {
            certificadoE = 1;
        }
        if (chxCertificadoJAC.isSelected()) {
            certificadoJAC = 1;
        }
        if (chxSisben.isSelected()) {
            sisben = 1;
        }
        if (chxOtros.isSelected()) {
            otros = 1;
        }
        //
        String usuario = txtusu.getText();
        String pn = txtPrimerNombre.getText();
        String sn = txtSegundoNombre.getText();
        String pa = txtPrimerApellido.getText();
        String sa = txtSegundoApellido.getText();
        String ident = txtIdentificacion.getText();
        int dep = Integer.parseInt(txtDepartamento.getText());
        int mun = Integer.parseInt(txtMunicipio.getText());
        String dir = txtDireccion.getText();
        String correo = txtCorreo.getText();
        int tramite = Integer.parseInt(txttramite.getText());
        String observaciones = observacion.getText();

        if (pn.equals("") || sn.equals("") || pa.equals("") || sa.equals("") || ident.equals("")
            || dep == 0 || mun == 0 || dir.equals("") || correo.equals("") || tramite == 0 || observaciones.equals("")) {
            JOptionPane.showMessageDialog(null, "Es necesario completar toda la informacion del solicitante");
        } else {
            if (count >= 3) {
                if (ctrl.registrar(pn, sn, pa, sa, ident, dep, mun, dir, correo, sisben, certificadoE, certificadoJAC, otros, tramite, observaciones, usuario)) {
                    JOptionPane.showMessageDialog(this, "Registro Guardado");
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al  Guardar");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Es necesario selecionar al menos 3 documentos");
            }
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        //        Rolsecretaria visprincipal = new Rolsecretaria();
        //        visprincipal.setVisible(true);
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frmRolAuxiliar.frmRegSol = null;
        frmRolsecretaria.frmRegSol = null;
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        frmRolAuxiliar.frmRegSol = null;
        frmRolsecretaria.frmRegSol = null;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistrosolicitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistrosolicitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistrosolicitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistrosolicitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistrosolicitante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Direcc;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Expedida;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cboTramite;
    private javax.swing.JComboBox<String> cbodepartamentos;
    private javax.swing.JComboBox<String> cbomunicipios;
    public javax.swing.JCheckBox chxCertificadoE;
    public javax.swing.JCheckBox chxCertificadoJAC;
    public javax.swing.JCheckBox chxOtros;
    public javax.swing.JCheckBox chxSisben;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabeltitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombresolicitante;
    public javax.swing.JTextField observacion;
    private javax.swing.JLabel primerapellido;
    private javax.swing.JLabel segundoapellido;
    private javax.swing.JLabel segundonombresolici;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtDepartamento;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtIdentificacion;
    public javax.swing.JTextField txtMunicipio;
    public javax.swing.JTextField txtPrimerApellido;
    public javax.swing.JTextField txtPrimerNombre;
    public javax.swing.JTextField txtSegundoApellido;
    public javax.swing.JTextField txtSegundoNombre;
    private javax.swing.JTextField txttramite;
    public static javax.swing.JTextField txtusu;
    // End of variables declaration//GEN-END:variables
}
