/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package certiboyaca.Vistalogin;

/**
 *
 * @author ALC_PTO_BOY
 */
public class interfazlogin extends javax.swing.JFrame {

    /**
     * Creates new form interfazlogin
     */
    public interfazlogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3icon = new javax.swing.JLabel();
        jLabelusu = new javax.swing.JLabel();
        jLabelcontra = new javax.swing.JLabel();
        jTextuser = new javax.swing.JTextField();
        jPasswor = new javax.swing.JPasswordField();
        jButto3iniciarsesion = new javax.swing.JButton();
        jLabelsubtitulo = new javax.swing.JLabel();
        jButtoneresnuevo = new javax.swing.JButton();
        jButtonrecupera = new javax.swing.JButton();
        jLabel2salir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("SALIR");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 80, 30));

        jLabel3icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CERTY111 (1).png"))); // NOI18N
        jLabel3icon.setText("jLabel1");
        getContentPane().add(jLabel3icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 30, 550, 320));

        jLabelusu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelusu.setForeground(new java.awt.Color(0, 0, 102));
        jLabelusu.setText("Usuario:");
        getContentPane().add(jLabelusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 110, -1));

        jLabelcontra.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelcontra.setForeground(new java.awt.Color(0, 0, 102));
        jLabelcontra.setText("Contraseña:");
        getContentPane().add(jLabelcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, 20));

        jTextuser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextuser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextuserActionPerformed(evt);
            }
        });
        getContentPane().add(jTextuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 180, -1));

        jPasswor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPasswor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPasswor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassworActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 180, 20));

        jButto3iniciarsesion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButto3iniciarsesion.setForeground(new java.awt.Color(0, 0, 102));
        jButto3iniciarsesion.setText("Iniciar sesión");
        jButto3iniciarsesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButto3iniciarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButto3iniciarsesionMouseClicked(evt);
            }
        });
        jButto3iniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButto3iniciarsesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButto3iniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 140, 30));

        jLabelsubtitulo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelsubtitulo.setForeground(new java.awt.Color(0, 0, 153));
        jLabelsubtitulo.setText("ALCALDÍA MUNICIPAL");
        getContentPane().add(jLabelsubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jButtoneresnuevo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtoneresnuevo.setForeground(new java.awt.Color(0, 0, 102));
        jButtoneresnuevo.setText("Soy nuevo");
        jButtoneresnuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtoneresnuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtoneresnuevoMouseClicked(evt);
            }
        });
        jButtoneresnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneresnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtoneresnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 190, 30));

        jButtonrecupera.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonrecupera.setForeground(new java.awt.Color(0, 0, 102));
        jButtonrecupera.setText("Recuperar contraseña");
        jButtonrecupera.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jButtonrecupera, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 200, 30));

        jLabel2salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1511.jpg"))); // NOI18N
        jLabel2salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPassworActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassworActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassworActionPerformed

    private void jTextuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextuserActionPerformed

    private void jButto3iniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButto3iniciarsesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButto3iniciarsesionActionPerformed

    private void jButto3iniciarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButto3iniciarsesionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButto3iniciarsesionMouseClicked

    private void jButtoneresnuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtoneresnuevoMouseClicked
       // TODO add your handling code here:
       Registrofuncionario fr=new Registrofuncionario();
       fr.setVisible(true);
       
    }//GEN-LAST:event_jButtoneresnuevoMouseClicked

    private void jButtoneresnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneresnuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtoneresnuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButto3iniciarsesion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtoneresnuevo;
    private javax.swing.JButton jButtonrecupera;
    private javax.swing.JLabel jLabel2salir;
    private javax.swing.JLabel jLabel3icon;
    private javax.swing.JLabel jLabelcontra;
    private javax.swing.JLabel jLabelsubtitulo;
    private javax.swing.JLabel jLabelusu;
    private javax.swing.JPasswordField jPasswor;
    private javax.swing.JTextField jTextuser;
    // End of variables declaration//GEN-END:variables
}
