/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package certiboyaca.Vistalogin;

/**
 *
 * @author ALC_PTO_BOY
 */
public class Registrofuncionario extends javax.swing.JFrame {

    /**
     * Creates new form Registrofuncionario
     */
    public Registrofuncionario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        datosnombres = new javax.swing.JTextField();
        apellidos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        datosapellidos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cargo = new javax.swing.JTextField();
        correo = new javax.swing.JLabel();
        datoscorreo = new javax.swing.JTextField();
        subtitulo = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        datosdireccion = new javax.swing.JTextField();
        telefono = new javax.swing.JLabel();
        datostelefono = new javax.swing.JTextField();
        constraseña = new javax.swing.JLabel();
        datoscontraseña = new javax.swing.JPasswordField();
        confcontraseña = new javax.swing.JLabel();
        datosconfircontraseña = new javax.swing.JPasswordField();
        fceharegistro = new javax.swing.JLabel();
        registrar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        identificacion = new javax.swing.JLabel();
        datosidentificacion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo.setText("REGISTRO PARA EL INGRESO AL SISTEMA");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 510, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nombres :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        datosnombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(datosnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 157, 270, -1));

        apellidos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        apellidos.setText("Apellidos :");
        getContentPane().add(apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logook.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, -1));

        datosapellidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(datosapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 157, 260, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Cargo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        cargo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 203, 210, 30));

        correo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        correo.setText("Correo electrónico:");
        getContentPane().add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 180, -1));

        datoscorreo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(datoscorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 190, 30));

        subtitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        subtitulo.setText("DATOS DEL FUNCIONARIO");
        getContentPane().add(subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        direccion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        direccion.setText("Dirección:");
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        datosdireccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(datosdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 260, 30));

        telefono.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        telefono.setText("Teléfono:");
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        datostelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(datostelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 287, 180, 30));

        constraseña.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        constraseña.setText("Asignar contraseña:");
        getContentPane().add(constraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        datoscontraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(datoscontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 170, 30));

        confcontraseña.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        confcontraseña.setText("Confirmar contraseña:");
        getContentPane().add(confcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, 20));

        datosconfircontraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(datosconfircontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 160, 30));

        fceharegistro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fceharegistro.setText("Fecha de registro:");
        getContentPane().add(fceharegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, 20));

        registrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        registrar.setText("Registrar usuario");
        registrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        getContentPane().add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 200, 40));

        cancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancelar.setText("Cancelar registro");
        cancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 200, 40));

        identificacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        identificacion.setText("Identificación:");
        getContentPane().add(identificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 20));

        datosidentificacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(datosidentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 190, 30));

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("SALIR");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 80, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1511.jpg"))); // NOI18N
        fondo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrofuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrofuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrofuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrofuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrofuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidos;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cargo;
    private javax.swing.JLabel confcontraseña;
    private javax.swing.JLabel constraseña;
    private javax.swing.JLabel correo;
    private javax.swing.JTextField datosapellidos;
    private javax.swing.JPasswordField datosconfircontraseña;
    private javax.swing.JPasswordField datoscontraseña;
    private javax.swing.JTextField datoscorreo;
    private javax.swing.JTextField datosdireccion;
    private javax.swing.JTextField datosidentificacion;
    private javax.swing.JTextField datosnombres;
    private javax.swing.JTextField datostelefono;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel fceharegistro;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel identificacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton registrar;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JLabel telefono;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
